version: "3.9"  # optional since v1.27.0
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    ports:
      - "15900:5910"
    env_file:
      - ./admin-token.env
    cap_add:
     - CAP_SYS_ADMIN