version: '3.7'

services:
  app:
    build: ./app/
    ports:
        - "127.0.0.1:80:8080"
    environment:
      - PORT=8080
      - WEB_CONCURRENCY=16
      - CHALL_HOST=tbdxss.chal.perfect.blue
      - SECRET_KEY=abcdbcdfd_cannot_gu355_t0p_s3cr3t_abcdcdcdcdcd
    depends_on:
      - redis

  bot:
    build: ./bot/
    init: true
    environment:
      - CHALL_HOST=tbdxss.chal.perfect.blue
      - CHALL_COOKIE=eyJub3RlIjoicGJjdGZ7ZzF0X20zXzRfcDRnM19yM2YzcjNuYzN9In0.YWCEbA.NIL3o5rrx5t7lQjODFzZxud7jA4
    depends_on:
      - redis

  redis:
    image: redis:6.0-alpine

